# Generated by Django 3.0.14 on 2022-09-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_at', models.DateField(auto_now_add=True, db_index=True)),
                ('will_post', models.DateField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets_created', to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
