# Generated by Django 3.0.14 on 2022-09-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220919_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
