# Generated by Django 3.0.14 on 2022-09-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_tweets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
