# Generated by Django 3.0.14 on 2022-09-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220920_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Tweets'},
        ),
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='will_post',
            field=models.DateTimeField(),
        ),
    ]
