# Generated by Django 3.0.14 on 2022-09-23 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220923_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='will_post_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
