# Generated by Django 3.0.14 on 2022-09-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220924_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='created_at_time',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='will_post_time',
        ),
    ]
