# Generated by Django 3.0.14 on 2022-09-24 10:45

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220924_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='will_post_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
