# Generated by Django 3.0.14 on 2022-09-24 16:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_tweets_created_at_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='will_post_time',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='will_post',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
    ]
