# Generated by Django 3.0.14 on 2022-09-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220925_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='will_post_time',
            field=models.IntegerField(default=0),
        ),
    ]
