# Generated by Django 3.0.14 on 2022-09-26 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_tweets_will_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='slug',
            field=models.SlugField(unique_for_date='publish'),
        ),
    ]
