# Generated by Django 3.0.14 on 2022-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20220926_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='will_post',
            field=models.DateTimeField(),
        ),
    ]
