# Generated by Django 3.0.14 on 2022-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220926_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='task_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
